name: Update Dynamic Profile README

on:
  schedule:
    - cron: "0 */6 * * *"   # updates every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate README Stats
        run: echo "Dynamic sections auto-refresh (GitHub stats, quotes, etc.)"

      - name: Commit and Push if Changes Exist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update dynamic data" && git push)
